[[mgr.prepend_keymap]]
on = "n"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "d"
run = "remove --permanently"
desc = "delete file"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"

[[mgr.prepend_keymap]]
on = "f"
run = "plugin smart-filter"
desc = "Smart filter plugin"

[[mgr.prepend_keymap]]
on = "F"
run = "filter"

[[mgr.prepend_keymap]]
on = ["<C-n>"]
run = '''
    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''
dec = "drage and drop files with ripdrag"

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = '''
    shell 'genisoimage -o ./output.iso -R -J "$@"' --confirm
'''

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads/"
dec = "cd to downloads"

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = "plugin mounter"

[[mgr.prepend_keymap]]
on = ["n"]
run = '''
    shell 'fzf&clear' --confirm
'''

[[mgr.prepend_keymap]]
on = ["g", "s"]
run = "plugin es_mounter"

[[mgr.prepend_keymap]]
on = ["g", "v"]
run = "cd ~/Videos/"
dec = "cd to downloads"

[[mgr.prepend_keymap]]
on = ["L"]
run = "plugin bypass"
desc = "Recursively enter child directory, skipping children with only a single subdirectory"

[[mgr.prepend_keymap]]
on = ["H"]
run = "plugin bypass --args=reverse"
desc = "Recursively enter parent directory, skipping parents with only a single subdirectory"

[[mgr.prepend_keymap]]
on = ["m", "t"]
run = "plugin what-size"
desc = "calc size of selection or cwd"

[[mgr.prepend_keymap]]
on = ["g", "f"]
run = "search_do --via=fd"
desc = "Switch to the flat view"

[[mgr.prepend_keymap]]
on = ["Y"]
run = "yank --cut"
desc = "yank"

[[mgr.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"

[[mgr.prepend_keymap]]
on = "O"
run = "plugin open-with-cmd"
desc = "Open with command"

[[mgr.prepend_keymap]]
on = "e"
run = "shell '$@' --confirm"
desc = "execute the current selected file"

[[mgr.prepend_keymap]]
on = ["c", "o"]
run = "shell 'codium $@' --confirm"
desc = "opens with codium"

[[mgr.prepend_keymap]]
on = ["c", "u"]
run = "cursor '$@' --confirm"
desc = "opens with cursor"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on = ["g", "n"]
run = 'shell -- ya emit reveal "$(readlink -f "$0")"'
desc = "Follow hovered symlink"
