[general]
auto_append = false

[ipc]
ipc_enabled_commands = [
  "mc",  # activate normal casing
  "sc",  # activate snake_casing
  "pm",  # activate ProperCasing
  "cm",  # activate camelCasing
  "us",  # activate UPPER_SNAKE_CASING
  "cb",  # clear buffer
  "sm",  # set main buffer
  "sr",  # set right buffer
  # "rl",  # reload config
  # "rs",  # restart program
]

[chips]
"rl" = ["reload_config"]
"-" = ["kebab-case-mode"]
# "nm" = ["normal case mode"]
"_" = ["snake_case_mode"]
"__" = ["UPPER_SNAKE_CASE_MODE"]
".." = ["backspace", ".", ".", ".", "space"]
"pm" = ["ProperCaseMode"]
"cmm" = ["cammelCaseMode"]
"ras" = ["restart"]
"'s" = ["backspace", "'", "s", "space"]
"'t" = ["backspace", "n", "'", "t", "space"]
"'l" = ["backspace", "'", "l", "l", "space"]
"'d" = ["backspace", "'", "d", "space"]
"at" = "at"
"it" = "it"
"in" = "in"
"is" = "is"
"of" = "of"
"to" = "to"
"so" = "so"
"be" = "be"
"into" = "into"
"do" = "do"
"us" = "us"
"an" = "an"
"by" = "by"
"up" = "up"
"or" = "or"
"go" = "go"
"he" = "he"
"me" = "me"
"if" = "if"
"we" = "we"
"as" = "as"
"am" = "am"
"my" = "my"
"his" = "his"
"i" = "I"
"o" = "on"
"n" = "no"
"js" = "just"
"nv" = "never"
"p" = "people"
"t" = "the"
"ad" = "and"
"u" = "you"
"y" = "yes"
"th" = "that"
"f" = "for"
"bu" = "but"
"ar" = "are"
"nt" = "not"
"ur" = "your"
"al" = "all"
"hv" = "have"
"aw" = "was"
"wht" = "with"
"ts" = "this"
"wt" = "what"
"ty" = "they"
"wn" = "when"
"c" = "can"
"kw" = "know"
"oe" = "one"
"te" = "there"
"x" = "they're"
"lk" = "like"
"wi" = "will"
"ig" = "it's"
"dn" = "don't"
"im" = "I'm"
"iv" = "I've"
"lf" = "life"
"frm" = "from"
"tm" = "time"
"ow" = "who"
"ou" = "out"
"m" = "them"
"ab" = "about"
"mr" = "more"
"yo" = "you're"
"hd" = "had"
"rj" = "our"
"ly" = "only"
"hw" = "how"
"tg" = "thing"
"g" = "get"
"eg" = "enough"
"se" = "see"
"wul" = "would"
"rw" = "were"
"wor" = "word"
"wrl" = "world"
"lv" = "live"
"ov" = "love"
"jt" = "than"
"ei" = "their"
"bj" = "because"
"bk" = "back"
"bl" = "black"
"bh" = "both"
"bo" = "before"
"tk" = "think"
"mk" = "make"
"e" = "then"
"sm" = "some"
"sg" = "something"
"bn" = "been"
"ej" = "end"
"ev" = "even"
"wy" = "way"
"gts" = "things"
"hm" = "him"
"cu" = "could"
"wnt" = "want"
"dy" = "day"
"hs" = "has"
"oj" = "other"
"ojs" = "others"
"aj" = "another"
"dif" = "different"
"ys" = "yes"
"ye" = "you're"
"b" = "be"
"yv" = "you've"
"Yv" = "You've"
"d" = "and"
"r" = "are"
"di" = "did"
"ng" = "nothing"
"ak" = "than"
"gr" = "great"
"ch" = "change"
"cc" = "chance"
"ec" = "each"
"af" = "after"
"wv" = "we've"
"wu" = "would"
"lg" = "long"
"eyg" = "everything"
"hn" = "haven't"
"cn" = "can't"
"cnn" = "cannot"
"sd" = "said"
"dt" = "didn't"
"sad" = "sad"
"ul" = "you'll"
"en" = "need"
"ths" = "that's"
"stm" = "sometime"
"sstm" = "sometimes"
"wrr" = "we're"
"dfy" = "differently"
"dfc" = "difficult"
"dfu" = "difficulty"
"nx" = "next"
"ox" = "own"
"ay" = "any"
"v" = "very"
"gj" = "give"
"va" = "gave"
"s" = "these"
"ag" = "anything"
"ug" = "young"
"ue" = "use"
"whr" = "where"
"md" = "made"
"sn" = "isn't"
"two" = "two"
"wut" = "without"
"wts" = "what's"
"ri" = "right"
"fj" = "find"
"tu" = "too"
"tp" = "top"
"lt" = "those"
"il" = "I'll"
"ill" = "ill"
"trs" = "there's"
"yrs" = "years"
"yr" = "year"
"wti" = "white"
"whl" = "while"
"bt" = "better"
"btn" = "button"
"h" = "here"
"y'" = "they're"
"cun" = "couldn't"
"avo" = "above"
"mv" = "move"
"mvg" = "moving"
"mvs" = "moves"
"agi" = "again"
"tag" = "tag"
"sag" = "sag"
"nag" = "nag"
"sat" = "sat"
"agj" = "against"
"ke" = "knew"
"kws" = "knows"
"gd" = "good"
"shl" = "should"
"bw" = "between"
"dw" = "down"
"sem" = "seem"
"wc" = "which"
"mo" = "most"
"mu" = "must"
"hev" = "however"
"kp" = "keep"
"le" = "leave"
"trh" = "through"
"mc" = "much"
"sc" = "since"
"sk" = "such"
"hot" = "hot"
"tgh" = "through"
"sin" = "sin"
"ji" = "interest"
"jic" = "increase"
"nm" = "name"
"bm" = "become"
"mba" = "became"
"nmb" = "number"
"gal" = "gal"
"lar" = "large"
"glr" = "general"
"ltt" = "little"
"stt" = "state"
"set" = "set"
"fs" = "first"
"hcl" = "child"
"she" = "she"
"say" = "say"
"man" = "man"
"men" = "men"
"new" = "new"
"k" = "take"
"com" = "com"
"cme" = "come"
"wrk" = "work"
"voe" = "over"
"hg" = "high"
"nnt" = "nation"
"pd" = "develop"
"ud" = "under"
"sam" = "same"
"bgk" = "background"
"big" = "big"
"bng" = "begin"
"pn" = "point"
"let" = "let"
"bp" = "public"
"pv" = "private"
"fll" = "follow"
"pso" = "possible"
"mps" = "impossible"
"msl" = "simple"
"ln" = "line"
"rn" = "return"
"rnn" = "\r\n"
"rnnn" = "\r\n\r\n"
